language: erlang

otp_release:
   - R16B

env:
  - LUA=""
  - LUA="luajit"

branches:
  only:
    - master

install:
  - sudo apt-get install luajit
  - sudo apt-get install luarocks
  - sudo luarocks install luafilesystem
  - sudo luarocks install busted

script: "busted --pattern=Spec test/specs"

notifications:
  recipients:
    - spence.dinicolantonio@gmail.com
  email:
    on_success: change
    on_failure: always
